build: Use `--disable-rofiles-fuse`
Using rofiles-fuse causes these errors:

```
Cleaning up
chmod: changing permissions of '/etc/pki/ca-trust/extracted/README': Read-only file system
chmod: changing permissions of '/etc/pki/ca-trust/extracted/edk2/README': Read-only file system
chmod: changing permissions of '/etc/pki/ca-trust/extracted/java/README': Read-only file system
chmod: changing permissions of '/etc/pki/ca-trust/extracted/pem/README': Read-only file system
Error: Child process exited with code 1
make: *** [Makefile:84: sdk] Error 1
```

Credit: https://discuss.kde.org/t/building-flatpak-kde-runtime/13413/2